#!/usr/bin/env python3
import requests
import os
import random
from datetime import datetime

print("🚀 Starting Neuraticles AI Content Generator...")

# Create articles directory
os.makedirs("articles", exist_ok=True)

# High-traffic topics
topics = [
    "AI Technology Trends 2024", 
    "Machine Learning Tutorials", 
    "Digital Marketing Strategies",
    "SEO Optimization Techniques",
    "ChatGPT Business Applications"
]

def generate_article():
    """Generate article using Hugging Face API with proper error handling"""
    api_key = os.getenv('HUGGINGFACE_API_KEY')
    if not api_key:
        return "HUGGINGFACE_API_KEY not found"
    
    topic = random.choice(topics)
    api_url = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2"
    headers = {"Authorization": f"Bearer {api_key}"}
    
    prompt = f"Write a short blog post about {topic} for 2024. Focus on practical tips."
    
    try:
        print(f"🤖 Generating article about: {topic}")
        response = requests.post(api_url, headers=headers, json={"inputs": prompt})
        
        if response.status_code == 200:
            result = response.json()
            if isinstance(result, list) and len(result) > 0:
                content = result[0].get('generated_text', 'No content generated')
                return f"# {topic}\n\n{content}\n\n*Generated by Neuraticles AI*"
        
        return f"# {topic}\n\nAPI returned status: {response.status_code}. Using fallback content.\n\nThis is a test article about {topic}. Real AI content coming soon!\n\n*Neuraticles AI System*"
        
    except Exception as e:
        return f"# {topic}\n\nError: {str(e)}\n\nFallback content about {topic}. AI system is initializing.\n\n*Neuraticles AI*"

# Generate 1-2 articles
num_articles = random.randint(1, 2)
print(f"📝 Generating {num_articles} articles...")

for i in range(num_articles):
    article_content = generate_article()
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    filename = f"articles/article-{timestamp}-{i+1}.md"
    
    with open(filename, "w") as f:
        f.write(article_content)
    
    print(f"✅ Created: {filename}")

print("🎉 AI Content Generation Complete!")
