#!/usr/bin/env python3
import requests
import json
import os
import random
from datetime import datetime

class NeuralContentGenerator:
    def __init__(self):
        self.api_key = os.getenv('HUGGINGFACE_API_KEY')
        self.api_url = "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2"
        self.headers = {"Authorization": f"Bearer {self.api_key}"}
        
        self.topics = [
            "AI Technology Trends 2024", "Machine Learning Tutorials", 
            "Digital Marketing Strategies", "SEO Optimization Techniques",
            "ChatGPT Prompts for Business", "Artificial Intelligence News",
            "Content Marketing Tips", "Social Media Marketing",
            "Google Algorithm Updates", "Website Traffic Generation"
        ]
    
    def generate_article(self):
        topic = random.choice(self.topics)
        prompt = f"Write a comprehensive SEO-optimized blog post about '{topic}' for 2024 with practical tips and examples. Format in markdown."
        
        try:
            response = requests.post(self.api_url, headers=self.headers, json={"inputs": prompt})
            if response.status_code == 200:
                return f"# {topic}\n\n{response.json()[0]['generated_text']}\n\n*Generated by Neuraticles AI*"
            else:
                return self.generate_fallback_article(topic)
        except:
            return self.generate_fallback_article(topic)
    
    def generate_fallback_article(self, topic):
        return f"""
# {topic}: Complete Guide for 2024

## Introduction
Discover how {topic} is transforming businesses in 2024. This AI-generated guide provides actionable insights.

## Key Benefits
- **Increased Efficiency** through automation
- **Better ROI** with data-driven strategies
- **Competitive Advantage** using latest trends

## Implementation Steps
1. **Research** current market trends
2. **Plan** your strategy
3. **Execute** with best practices
4. **Analyze** and optimize results

## Conclusion
{topic} offers significant opportunities in 2024. Start implementing today!

*Automatically generated by Neuraticles AI*
"""

def main():
    print("🚀 Starting AI Content Generation...")
    ai = NeuralContentGenerator()
    
    for i in range(2):
        article = ai.generate_article()
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        filename = f"articles/article-{timestamp}-{i+1}.md"
        
        os.makedirs("articles", exist_ok=True)
        with open(filename, "w") as f:
            f.write(article)
        print(f"✅ Generated: {filename}")

if __name__ == "__main__":
    main()
